### ISSUE TITLE
client.verify() fails on 0.1.15

### ISSUE THREAD

**Issue by vshymanskyy** [hirotakaster/TlsTcpClient#2]
Thanks for a great library!
My `client.verify()` fails on 0.1.15. When i switch back to 0.1.14 - it works fine.
I use Let's Encrypt, the same server and same sketch. Only library version differs.
Would be grateful for any help.
Verification fails, but the server gets a correct request afterwards.

**Comment by hirotakaster** [comment]
Hi @vshymanskyy 
okay, I will check.

**Comment by hirotakaster** [comment]
hi @vshymanskyy 
update to 0.1.16. verify works fine. thank you for your report.

**Comment by vshymanskyy** [comment]
Thank you so much! ;) I'll close it once verified

**Comment by vshymanskyy** [comment]
Verified. Thanks again!
