### ISSUE TITLE
undefined reference to `mbedtls_debug_set_threshold'

### ISSUE THREAD

**Issue by Fiebbo** [hirotakaster/TlsTcpClient#6]
Thank you for porting this awesome library to particle,

When trying to build this in particle workbench with debug enabled I get the following message:
> undefined reference to 'mbedtls_debug_set_threshold'

I have `#define MBEDTLS_DEBUG_C` and `#include mbedtls/debug.h`

I'm using a particle Boron with deviceOS 1.4.0

**Comment by hirotakaster** [comment]
Hi @Fiebbo ,
Thank you for your report. I will check on VScode.

**Comment by hirotakaster** [comment]
Please set (not a mbedtls/debug.h)
`#define MBEDTLS_DEBUG_C ` at  `mbedtls/config.h`

Now I find other compile error on `mbedtls/config.h` and fixed it.
update version 0.2.15 on Particle library.

**Comment by Fiebbo** [comment]
Thanks @hirotakaster , debug output works now.
